name: mlc test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            build_type: Release
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            build_type: Release
            c_compiler: gcc-14
            cpp_compiler: g++-14
          - os: windows-latest
            build_type: Release
            c_compiler: clang-cl
            cpp_compiler: clang-cl
          - os: ubuntu-latest
            build_type: Release
            c_compiler: clang-20
            cpp_compiler: clang++-20

    steps:
    - uses: actions/checkout@v4

    - name: Set up build directory
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Setup GCC 14 on Linux
      if: matrix.os == 'ubuntu-latest' && matrix.c_compiler == 'gcc-14'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-14 g++-14 clang
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
        gcc --version
        g++ --version
    - name: Setup Clang on Linux
      if: matrix.os == 'ubuntu-latest' && matrix.c_compiler == 'clang-20'
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 20
        clang-20 --version

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      if: matrix.os == 'ubuntu-latest'
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ./mlc-test

    - name: Test
      if: matrix.os == 'windows-latest'
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      shell: powershell
      run: .\Release\mlc-test.exe

