name: mlc test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc-14, cl, clang]
        cpp_compiler: [g++-14, cl, clang]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: windows-latest
            c_compiler: clang
            cpp_compiler: clang
          - os: ubuntu-latest
            c_compiler: gcc-14
            cpp_compiler: g++-14
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang
        exclude:
          - os: windows-latest
            c_compiler: gcc-14
          - os: windows-latest
            c_compiler: clang
            cpp_compiler: cl
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: clang
          - os: windows-latest
            cpp_compiler: g++-14
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: g++-14
          - os: ubuntu-latest
            c_compiler: gcc-14
            cpp_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl
          - os: ubuntu-latest
            cpp_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Set up build directory
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Setup GCC 14 on Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-14 g++-14 clang
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
        gcc --version
        g++ --version

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      if: matrix.os == 'ubuntu-latest'
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ./mlc-test

    - name: Test
      if: matrix.os == 'windows-latest'
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      shell: powershell
      run: .\Release\mlc-test.exe

